main: main.java.com.mortuusterra.MortuusTerraMain
name: MortuusTerra
version: 1.0.0
author: Kadeska23
depends: []
softdepends: []
database: false
description: Plugin for Mortuus Terra 
commands:
  channel:
    description: Base command for sellecting a chat channel
    usage: /channel
  mortuusterra:
    description: Base command for mortuusterra
    usage: /mortuusterra
